# Generated by Django 3.2.3 on 2021-06-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(verbose_name='monto')),
                ('estado', models.IntegerField(choices=[(0, 'Procesando'), (1, 'Realizada'), (2, 'Rechazada')], verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de realizacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_realizada', to='core.cuenta', verbose_name='Transacciones realizada')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='core.cuenta', verbose_name='Transacciones recibidas')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
