# Generated by Django 3.2.3 on 2021-06-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cuenta_user'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_realizada', to='core.cuenta', verbose_name='Emisor'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Procesando'), (1, 'Realizada'), (2, 'Rechazada')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='core.cuenta', verbose_name='Receptor'),
        ),
    ]
