services:
    front:
        build: ./front
        command: >
          yarn start
        volumes:
            - ./front:/code
        ports:
            - "${FRONT_PORT:-3000}:3000"
        environment: 
            - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-8000}
        depends_on:
            - web
    web:
        build: ./api
        command: >
         sh -c "pipenv run start"
        volumes: 
            - ./api:/code
        ports: 
            - "${BACKEND_PORT:-8000}:8000"
        depends_on:
            - db
        environment:
            - DEBUG=${DEBUG}
            - FRONT_PORT=${FRONT_PORT:-3000}
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=challenge
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    redis:
        image: redis
    celery:
        build:
            context: ./api
        command: pipenv run celery -A challenge worker -l info
        volumes: 
            - ./api:/code
        depends_on:
            - db
            - redis
            - web

    